In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd
from io import StringIO

In [11]:
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
0.0,11.0,12.0'''

In [12]:
csv_data = unicode(csv_data)
df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [13]:
df.isnull()

A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

In [14]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [15]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [ 0., 11., 12., nan]])

In [16]:
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [18]:
df.dropna()

A    B    C    D
0  1.0  2.0  3.0  4.0

In [19]:
df.dropna(axis=1)

A     B
0  1.0   2.0
1  5.0   6.0
2  0.0  11.0

In [20]:
#only drop rows where columns are NaN
df.dropna(how='all')


A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [21]:
#drop rows that do not have atleast 4 non NaN values
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [22]:
#only drop rows where NaN appear in specific columns
df.dropna(subset=['C'])

A     B     C    D
0  1.0   2.0   3.0  4.0
2  0.0  11.0  12.0  NaN

In [23]:
df

A     B     C    D
0  1.0   2.0   3.0  4.0
1  5.0   6.0   NaN  8.0
2  0.0  11.0  12.0  NaN

In [26]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean',axis = 0)
imputer = imputer.fit(df)
imputed_data = imputer.transform(df.values)
imputed_data

C:\Users\10645164\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [ 0. , 11. , 12. ,  6. ]])

In [27]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values='NaN', strategy='mean',axis = 1)
imputer = imputer.fit(df)
imputed_data = imputer.transform(df.values)
imputed_data

C:\Users\10645164\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  6.33333333,  8.        ],
       [ 0.        , 11.        , 12.        ,  7.66666667]])